POST http://localhost:3000/reports
content-type: application/json

{
    "make": "Hyndai",
    "model" : "N79",
    "year": 1980,
    "mileage": 100000,
    "lng": 0,
    "lat": 0,
    "price": 500000
}


PATCH http://localhost:3000/reports/{id}
content-type: application/json
{
    "approved": true
}