### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "asdf@asdf.com",
  "password": "asdlfkajsd"
}



### Find a particular User with a given ID
GET http://localhost:3000/auth/1


### Find a All User
GET http://localhost:3000/auth?email=asdf@asdf.com


### Delete particular User
DELETE http://localhost:3000/auth/1


### Update User
UPDATE http://localhost:3000/auth/1

content-type: application/json

{
  "email": "aaaaa@aaaa.com"
}